[build]
publish = ".next"
command = "npm run build"

[[redirects]]
from = "/test"
to = "https://httpbin.org/headers"
status = 200
force = true

[[redirects]]
from = "/_next/static/*"
to = "/_next/static/:splat"
status = 200
force = true
