[build]
  publish = ".next"
  command = "npm run build"

  [[plugins]]
  package = "./plugins/redirect-plugin"

  [[redirects]]
  from = "/test/*"
  to = "/https://httpbin.org/headers"
  status = 200!